# Generated by Django 3.0.3 on 2020-03-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollumeterbeta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='fac_JAM',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='pol_bc',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='pol_no',
        ),
        migrations.AddField(
            model_name='pollimetermodel',
            name='measurement_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
