# Generated by Django 3.0.3 on 2020-03-14 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollumeterbeta', '0004_auto_20200314_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollimetermodel',
            old_name='pol_aqi',
            new_name='aqi',
        ),
    ]
