# Generated by Django 3.0.4 on 2020-03-15 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollumeterbeta', '0006_auto_20200314_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollimetermodel',
            old_name='fac_avg_speed',
            new_name='indpro',
        ),
        migrations.RenameField(
            model_name='pollimetermodel',
            old_name='fac_indfert',
            new_name='traf',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='fac_indfood',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='fac_indman',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='fac_indpharm',
        ),
        migrations.RemoveField(
            model_name='pollimetermodel',
            name='fac_indtech',
        ),
    ]
