# Generated by Django 3.0.4 on 2020-03-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollumeterbeta', '0007_auto_20200315_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='bar_char',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traf', models.FloatField()),
                ('industrialproduction', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='predicted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aqi', models.FloatField()),
                ('aqi2', models.FloatField()),
                ('aqi3', models.FloatField()),
                ('aqi4', models.FloatField()),
            ],
        ),
    ]
